# Generated by rust2rpm 26
%bcond_without check

%global pkgname verdi

%global commit 998d3c4cf5c6e00f661ba59a545e1da9241cd110
%global shortcommit %(c=%{commit}; echo ${c:0:7})
%global ver 0.0.1

Name:           %{pkgname}-git
Version:        %{ver}.git.%{shortcommit}
Release:        %autorelease
Summary:        The elegant wayland compositor

License:        Apache-2.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/verdiwm/verdi
Source:         %{url}/archive/%{commit}/%{pkgname}-%{shortcommit}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  curl

Requires:       libinput

Conflicts:      verdi
Provides:       verdi

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{pkgname}-%{commit} -p1
# Install and enable rustup for nightly
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
. "$HOME/.cargo/env"
rustup toolchain link system /usr
# vendor dependencies
cargo vendor
%cargo_prep -v vendor

%build
cargo build --locked --release
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
install -Dpm755 target/release/%{pkgname} %{buildroot}%{bindir}/%{pkgname}

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/%{pkgname}

%changelog
%autochangelog
