# Generated by rust2rpm 26
%bcond_without check

Name:           yazi
Version:        0.2.5
Release:        %autorelease
Summary:        Yazi File Manager

# FIXME: paste output of %%cargo_license_summary here
License:        MIT
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/sxyazi/yazi
Source:         %{url}/archive/v%{version}/%{name}-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  make
Buildrequires:  gcc

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{name}-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
export YAZI_GEN_COMPLETIONS=1
cargo build -p yazi-fm -p yazi-cli --locked --release
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
install -Dpm755 target/release/%{name} %{buildroot}%{_bindir}/%{name}
install -Dpm755 target/release/ya %{buildroot}%{_bindir}/ya
install -Dpm644 yazi-cli/completions/_ya %{buildroot}%{zsh_completions_dir}/_ya
install -Dpm644 yazi-cli/completions/ya.bash %{buildroot}%{bash_completions_dir}/ya.bash
install -Dpm644 yazi-cli/completions/ya.fish %{buildroot}%{fish_completions_dir}/ya.fish
install -Dpm644 yazi-boot/completions/_%{name} %{buildroot}%{zsh_completions_dir}/_%{name}
install -Dpm644 yazi-boot/completions/%{name}.bash %{buildroot}%{bash_completions_dir}/%{name}.bash
install -Dpm644 yazi-boot/completions/%{name}.fish %{buildroot}%{fish_completions_dir}/%{name}.fish

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/ya
%{_bindir}/yazi
%{zsh_completions_dir}/_ya
%{bash_completions_dir}/ya.bash
%{fish_completions_dir}/ya.fish
%{zsh_completions_dir}/_%{name}
%{bash_completions_dir}/%{name}.bash
%{fish_completions_dir}/%{name}.fish

%changelog
%autochangelog
